# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Even"
license = "MIT"
licenselink = "https://github.com/olOwOlo/hugo-theme-even/blob/master/LICENSE.md"
description = "A super concise theme for Hugo"
homepage = "https://github.com/olOwOlo/hugo-theme-even"
tags = ["responsive", "blog", "simple", "clean", "highlight.js", "syntax highlighting"]
features = ["responsive", "blog", "simple", "clean", "highlight.js", "syntax highlighting"]
min_version = "0.60.0"

[author]
  name = "olOwOlo"
  homepage = "https://github.com/olOwOlo"

# If porting an existing theme
[original]
  name = "hexo-theme-even"
  homepage = "http://www.ahonn.me/"
  repo = "https://github.com/ahonn/hexo-theme-even"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ""
    footnoteReturnLinkContents = ""
    fractions = true
    hrefTargetBlank = false
    latexDashes = true
    nofollowLinks = false
    noreferrerLinks = false
    plainIDAnchors = true
    skipHTML = false
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6
